# Use the official MySQL image
FROM mysql:latest

# Set environment variables (replace with your desired values)
ENV MYSQL_ROOT_PASSWORD=root_password
ENV MYSQL_DATABASE=hotelmanagement
ENV MYSQL_USER=hotelmanagement_user
ENV MYSQL_PASSWORD=hotelmanagement_password

# Copy SQL script to initialize database
COPY ./backend/hotelmanagement.sql /docker-entrypoint-initdb.d/

# Expose MySQL default port
EXPOSE 3306
