# Use Node.js LTS version as the base image
FROM node:lts

# Set working directory
WORKDIR /app

# Copy package.json and package-lock.json to the working directory
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application code
COPY . .

# Expose the port on which your backend API will run
EXPOSE 3067

# Command to run the backend server
CMD ["node", "index.js"]
