version: '3'

services:
  backend:
    build: .
    ports:
      - "3067:3067"  
    environment:
      - NODE_ENV=production
      - DB_HOST=db  # Updated to use the hostname of the database service
      - DB_USER=root
      - DB_PASSWORD=yvan2021
      - DB_NAME=hotelmanagement
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=yvan2021
    ports:
      - "3306:3306"
    volumes:
      - ./hotelmanagement.sql:/docker-entrypoint-initdb.d/hotelmanagement.sql
