# Use the official Node.js image as base
FROM node:16

# Set the working directory inside the container
WORKDIR /app

# Copy package.json and package-lock.json to the working directory
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application code
COPY . .

# Expose port 3000 (or whichever port your backend API listens on)
EXPOSE 3067

# Define the startup command
CMD ["node", "index.js"]
